/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package roster;
import java.io.*;
import java.util.*;
import java.sql.*;

/**
 *
 * @author shahua
 */
public class addspecial extends javax.swing.JFrame {

    /**
     * Creates new form addstaff
     */
    public addspecial() {
        //this.<error> = null;
        
        initComponents();
        //System.out.println("let's go");
        //new addspecial().dispose();
        
        load_name(); // load all the staff name
        load_specail(); //load all special requirement
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jComboBox1 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setState(-1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ABERFOYLE PARK", "WILLUNGA", "WOODCROFT", "NOARLUNGA" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jCheckBox1.setText("Monday");
        jCheckBox1.setToolTipText("");
        jCheckBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox1ItemStateChanged(evt);
            }
        });
        jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1MouseClicked(evt);
            }
        });

        jCheckBox2.setText("Tuesday");
        jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox2ItemStateChanged(evt);
            }
        });
        jCheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox2MouseClicked(evt);
            }
        });
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("Wednesday");
        jCheckBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox3ItemStateChanged(evt);
            }
        });
        jCheckBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox3MouseClicked(evt);
            }
        });

        jCheckBox4.setText("Thursday");
        jCheckBox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox4ItemStateChanged(evt);
            }
        });
        jCheckBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox4MouseClicked(evt);
            }
        });

        jCheckBox5.setText("Friday");
        jCheckBox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox5ItemStateChanged(evt);
            }
        });
        jCheckBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox5MouseClicked(evt);
            }
        });

        jCheckBox6.setText("Monday");
        jCheckBox6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox6ItemStateChanged(evt);
            }
        });
        jCheckBox6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox6MouseClicked(evt);
            }
        });

        jCheckBox7.setText("Tuesday");
        jCheckBox7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox7ItemStateChanged(evt);
            }
        });
        jCheckBox7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox7MouseClicked(evt);
            }
        });

        jCheckBox8.setText("Wednesday");
        jCheckBox8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox8ItemStateChanged(evt);
            }
        });
        jCheckBox8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox8MouseClicked(evt);
            }
        });

        jCheckBox9.setText("Thursday");
        jCheckBox9.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox9ItemStateChanged(evt);
            }
        });
        jCheckBox9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox9MouseClicked(evt);
            }
        });

        jCheckBox10.setText("Friday");
        jCheckBox10.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox10ItemStateChanged(evt);
            }
        });
        jCheckBox10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox10MouseClicked(evt);
            }
        });

        jCheckBox11.setText("Monday");
        jCheckBox11.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox11ItemStateChanged(evt);
            }
        });
        jCheckBox11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox11MouseClicked(evt);
            }
        });

        jCheckBox13.setText("Tuesday");
        jCheckBox13.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox13ItemStateChanged(evt);
            }
        });
        jCheckBox13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox13MouseClicked(evt);
            }
        });

        jCheckBox14.setText("Wednesday");
        jCheckBox14.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox14ItemStateChanged(evt);
            }
        });
        jCheckBox14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox14MouseClicked(evt);
            }
        });

        jCheckBox15.setText("Thursday");
        jCheckBox15.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox15ItemStateChanged(evt);
            }
        });
        jCheckBox15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox15MouseClicked(evt);
            }
        });

        jCheckBox16.setText("Friday");
        jCheckBox16.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox16ItemStateChanged(evt);
            }
        });
        jCheckBox16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox16MouseClicked(evt);
            }
        });

        jCheckBox17.setText("Monday");
        jCheckBox17.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox17ItemStateChanged(evt);
            }
        });
        jCheckBox17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox17MouseClicked(evt);
            }
        });

        jCheckBox18.setText("Tuesday");
        jCheckBox18.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox18ItemStateChanged(evt);
            }
        });
        jCheckBox18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox18MouseClicked(evt);
            }
        });

        jCheckBox19.setText("Wednesday");
        jCheckBox19.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox19ItemStateChanged(evt);
            }
        });
        jCheckBox19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox19MouseClicked(evt);
            }
        });

        jCheckBox20.setText("Thursday");
        jCheckBox20.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox20ItemStateChanged(evt);
            }
        });
        jCheckBox20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox20MouseClicked(evt);
            }
        });

        jCheckBox21.setText("Friday");
        jCheckBox21.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckBox21ItemStateChanged(evt);
            }
        });
        jCheckBox21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox21MouseClicked(evt);
            }
        });

        jButton1.setText("save");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("reset");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("name");

        jLabel2.setText("Location");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jComboBox2.setToolTipText("");
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "COORD", "AW", "AL", "PL", "LSL", "OFFLINE", "CC1", "CC2", "CC3", "CC4", "CC5", "CC6", "CC7", "CC8", "CC9", "CCB", "FC1", "FC2", "FC3", "FC2N", "FC2CC", "FC2BU" }));
        jComboBox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox3ItemStateChanged(evt);
            }
        });

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenu4.setToolTipText("");
        jMenu4.setName(""); // NOI18N

        jMenuItem1.setText("Add New");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseEntered(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar2.add(jMenu4);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(181, 181, 181))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jScrollPane2))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(98, 98, 98))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox5)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox8)
                            .addComponent(jCheckBox9)
                            .addComponent(jCheckBox10))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCheckBox13)
                                .addComponent(jCheckBox14)
                                .addComponent(jCheckBox15)
                                .addComponent(jCheckBox16))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCheckBox11)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox17)
                            .addComponent(jCheckBox18)
                            .addComponent(jCheckBox19)
                            .addComponent(jCheckBox20)
                            .addComponent(jCheckBox21))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1MouseClicked
       // TODO add your handling code here:
     
       // jTextArea1.append(working_day[1] + "   "+((String)jList1.getSelectedValue())+"\n");
        
        
        if(jCheckBox1.isSelected()){
            special=add_special("mon_w1");
        }else{
            special=del_special("mon_w1");
        }
            
    }//GEN-LAST:event_jCheckBox1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        jTextArea1.setText(null);
        
        //jList1.setSelectedIndex(0);
        
        jComboBox1.setSelectedIndex(0);
        jComboBox2.setSelectedIndex(0);
        jComboBox3.setSelectedIndex(0);
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);
        jCheckBox8.setSelected(false);
        jCheckBox9.setSelected(false);
        jCheckBox10.setSelected(false);
        jCheckBox11.setSelected(false);
        
        jCheckBox13.setSelected(false);
        jCheckBox14.setSelected(false);
        jCheckBox15.setSelected(false);
        jCheckBox16.setSelected(false);
        jCheckBox17.setSelected(false);
        jCheckBox18.setSelected(false);
        jCheckBox19.setSelected(false);
        jCheckBox20.setSelected(false);
        jCheckBox21.setSelected(false);
        
        jCheckBox1.setEnabled(true);
        jCheckBox2.setEnabled(true);
        jCheckBox3.setEnabled(true);
        jCheckBox4.setEnabled(true);
        jCheckBox5.setEnabled(true);
        jCheckBox6.setEnabled(true);
        jCheckBox7.setEnabled(true);
        jCheckBox8.setEnabled(true);
        jCheckBox9.setEnabled(true);
        jCheckBox10.setEnabled(true);
        jCheckBox11.setEnabled(true);
        
        jCheckBox13.setEnabled(true);
        jCheckBox14.setEnabled(true);
        jCheckBox15.setEnabled(true);
        jCheckBox16.setEnabled(true);
        jCheckBox17.setEnabled(true);
        jCheckBox18.setEnabled(true);
        jCheckBox19.setEnabled(true);
        jCheckBox20.setEnabled(true);
        jCheckBox21.setEnabled(true);
        
        jButton1.setEnabled(true);
        //jTextArea1.append("remove");
        
         //?
        positions_baseday=new ArrayList<String>();  //should be [][]
        
      
    
        base=new ArrayList<ArrayList<String>>();     //the positions of base or nonbase day in each location
        nonbase=new ArrayList<ArrayList<String>>();
        for(int i=0;i<4;i++)// 4 locations
        {base.add(new ArrayList<String>());nonbase.add(new ArrayList<String>());}
               
        name="";      //person's name 
        location="";  //get location from list
        
        
         //all information about the person
        working_day = new String[21]; //the base day or nonbase...
        //int amount_position=16; //number of position (cc1 cc2 ...)
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox2MouseClicked
        // TODO add your handling code here:
         if(jCheckBox2.isSelected()){
            special=add_special("tue_w1");
        }else{
            special=del_special("tue_w1");
        }
    }//GEN-LAST:event_jCheckBox2MouseClicked

    private void jCheckBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox3MouseClicked
        // TODO add your handling code here:
          if(jCheckBox3.isSelected()){
            special=add_special("wed_w1");
        }else{
            special=del_special("wed_w1");
        }
    }//GEN-LAST:event_jCheckBox3MouseClicked

    private void jCheckBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox4MouseClicked
        // TODO add your handling code here:
          if(jCheckBox4.isSelected()){
            special=add_special("thur_w1");
        }else{
            special=del_special("thur_w1");
        }

    }//GEN-LAST:event_jCheckBox4MouseClicked

    private void jCheckBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox5MouseClicked
        // TODO add your handling code here:
         if(jCheckBox5.isSelected()){
            special=add_special("fri_w1");
        }else{
            special=del_special("fri_w1");
        }
    }//GEN-LAST:event_jCheckBox5MouseClicked

    private void jCheckBox6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox6MouseClicked
        // TODO add your handling code here:
           if(jCheckBox6.isSelected()){
            special=add_special("mon_w2");
        }else{
            special=del_special("mon_w2");
        }
    }//GEN-LAST:event_jCheckBox6MouseClicked

    private void jCheckBox7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox7MouseClicked
        // TODO add your handling code here:
          if(jCheckBox7.isSelected()){
            special=add_special("tue_w2");
        }else{
            special=del_special("tue_w2");
        }   
    }//GEN-LAST:event_jCheckBox7MouseClicked

    private void jCheckBox8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox8MouseClicked
        // TODO add your handling code here:
          if(jCheckBox8.isSelected()){
            special=add_special("wed_w2");
        }else{
            special=del_special("wed_w2");
        }   
    }//GEN-LAST:event_jCheckBox8MouseClicked

    private void jCheckBox9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox9MouseClicked
        // TODO add your handling code here:
          if(jCheckBox9.isSelected()){
            special=add_special("thur_w2");
        }else{
            special=del_special("thur_w2");
        } 
    }//GEN-LAST:event_jCheckBox9MouseClicked

    private void jCheckBox10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox10MouseClicked
        // TODO add your handling code here:
          if(jCheckBox10.isSelected()){
            special=add_special("fri_w2");
        }else{
            special=del_special("fri_w2");
        }   
    }//GEN-LAST:event_jCheckBox10MouseClicked

    private void jCheckBox11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox11MouseClicked
        // TODO add your handling code here:
         if(jCheckBox11.isSelected()){
            special=add_special("mon_w3");
        }else{
            special=del_special("mon_w3");
        }
    }//GEN-LAST:event_jCheckBox11MouseClicked

    private void jCheckBox13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox13MouseClicked
        // TODO add your handling code here:
          if(jCheckBox13.isSelected()){
            special=add_special("tue_w3");
        }else{
            special=del_special("tue_w3");
        }
    }//GEN-LAST:event_jCheckBox13MouseClicked

    private void jCheckBox14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox14MouseClicked
        // TODO add your handling code here:
         if(jCheckBox14.isSelected()){
            special=add_special("wed_w3");
        }else{
            special=del_special("wed_w3");
        }
    }//GEN-LAST:event_jCheckBox14MouseClicked

    private void jCheckBox15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox15MouseClicked
        // TODO add your handling code here:
         if(jCheckBox15.isSelected()){
            special=add_special("thur_w3");
        }else{
            special=del_special("thur_w3");
        }
    }//GEN-LAST:event_jCheckBox15MouseClicked

    private void jCheckBox16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox16MouseClicked
        // TODO add your handling code here:
         if(jCheckBox16.isSelected()){
            special=add_special("fri_w3");
        }else{
            special=del_special("fri_w3");
        }
    }//GEN-LAST:event_jCheckBox16MouseClicked

    private void jCheckBox17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox17MouseClicked
        // TODO add your handling code here:
          if(jCheckBox17.isSelected()){
            special=add_special("mon_w4");
        }else{
            special=del_special("mon_w4");
        }
    }//GEN-LAST:event_jCheckBox17MouseClicked

    private void jCheckBox18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox18MouseClicked
        // TODO add your handling code here:
          if(jCheckBox18.isSelected()){
            special=add_special("tue_w4");
        }else{
            special=del_special("tue_w4");
        }
       
    }//GEN-LAST:event_jCheckBox18MouseClicked

    private void jCheckBox19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox19MouseClicked
        // TODO add your handling code here:
         if(jCheckBox19.isSelected()){
            special=add_special("wed_w4");
        }else{
            special=del_special("wed_w4");
        }
    }//GEN-LAST:event_jCheckBox19MouseClicked

    private void jCheckBox20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox20MouseClicked
        // TODO add your handling code here:
         if(jCheckBox20.isSelected()){
            special=add_special("thur_w4");
        }else{
            special=del_special("thur_w4");
        }
    }//GEN-LAST:event_jCheckBox20MouseClicked

    private void jCheckBox21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox21MouseClicked
        // TODO add your handling code here:
          if(jCheckBox21.isSelected()){
            special=add_special("fri_w4");
        }else{
            special=del_special("fri_w4");
        }
        
    }//GEN-LAST:event_jCheckBox21MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Connection conn = null;
        try {
//        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

       // DB d=new DB();
        } catch (java.lang.ClassNotFoundException e) {
            e.printStackTrace();
        }
        //System.out.println("ssssss  ");
        try {
            //conn = DriverManager.getConnection("jdbc:odbc:dbpoolname",  "sa", "123456");  
            conn = DriverManager.getConnection("jdbc:sqlserver://testsql:1433;DatabaseName5=roster", "shahua", "4321");
            System.out.println("connected");
        } catch (SQLException e) {
            System.out.println(e);
        }
        
        //delete
         String q="use roster delete from specialrequire";
        try{
            Statement stmt = conn.createStatement();
            PreparedStatement pstmt = null;
            pstmt=conn.prepareCall(q);
            pstmt.executeUpdate();
            
            stmt.close();
            conn.close();
            //System.out.println("deleted ");
        }catch(Exception e){
            System.out.println(e);
        }
        
        
        try {
//        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

       // DB d=new DB();
        } catch (java.lang.ClassNotFoundException e) {
            e.printStackTrace();
        }
        //System.out.println("ssssss  ");
        try {
            //conn = DriverManager.getConnection("jdbc:odbc:dbpoolname",  "sa", "123456");  
            conn = DriverManager.getConnection("jdbc:sqlserver://testsql:1433;DatabaseName5=roster", "shahua", "4321");
            //System.out.println("connected");
        } catch (SQLException e) {
            System.out.println(e);
        }
        
       //insert
       // conn=null;
        
        for(int i=0;i<special.size();i++){
         q="use roster insert into specialrequire (name,location,position,day) values ('"+special.get(i)[0]+"','"+special.get(i)[1]+"','"+special.get(i)[2]+"','"+special.get(i)[3]+"')";
         //System.out.println(q);
        try{
            Statement stmt = conn.createStatement();
            PreparedStatement pstmt = null;
            pstmt=conn.prepareCall(q);
            pstmt.executeUpdate();
            
            stmt.close();
            //conn.close();
            //System.out.println("inserted");
        }catch (Exception e){
            System.out.println(e);
        }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jCheckBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox1ItemStateChanged
        // TODO add your handling code here:
           
    }//GEN-LAST:event_jCheckBox1ItemStateChanged

    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox2ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox2ItemStateChanged

    private void jCheckBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox3ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox3ItemStateChanged

    private void jCheckBox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox4ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox4ItemStateChanged

    private void jCheckBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox5ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox5ItemStateChanged

    private void jCheckBox6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox6ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox6ItemStateChanged

    private void jCheckBox7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox7ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox7ItemStateChanged

    private void jCheckBox8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox8ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox8ItemStateChanged

    private void jCheckBox9ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox9ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox9ItemStateChanged

    private void jCheckBox10ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox10ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox10ItemStateChanged

    private void jCheckBox11ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox11ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox11ItemStateChanged

    private void jCheckBox13ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox13ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox13ItemStateChanged

    private void jCheckBox14ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox14ItemStateChanged
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jCheckBox14ItemStateChanged

    private void jCheckBox15ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox15ItemStateChanged
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jCheckBox15ItemStateChanged

    private void jCheckBox16ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox16ItemStateChanged
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jCheckBox16ItemStateChanged

    private void jCheckBox17ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox17ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox17ItemStateChanged

    private void jCheckBox18ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox18ItemStateChanged
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jCheckBox18ItemStateChanged

    private void jCheckBox19ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox19ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox19ItemStateChanged

    private void jCheckBox20ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox20ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox20ItemStateChanged

    private void jCheckBox21ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox21ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jCheckBox21ItemStateChanged

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        // TODO add your handling code here:
       
        
    
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseEntered
        // TODO add your handling code here:
         System.out.println("   bbbbbb");
       //jButton1.addActionListener(new java.awt.event.ActionListener() {   public void actionPerformed(java.awt.event.ActionEvent e) {new addspecial().setVisible(ture);}});
        jMenuItem1.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent e){
               new addspecial().setVisible(false);
             // addspecial();
                //new addstaff1().setVisible(true);
                 
                //System.exit(0);
               //new addstaff().setVisible(rootPaneCheckingEnabled);
               // new addspecial().dispose();
            }
        });
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1MouseEntered

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
        jTextArea1.setText(null);
        
        //jComboBox2.setSelectedIndex(0);
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);
        jCheckBox8.setSelected(false);
        jCheckBox9.setSelected(false);
        jCheckBox10.setSelected(false);
        jCheckBox11.setSelected(false);
        
        jCheckBox13.setSelected(false);
        jCheckBox14.setSelected(false);
        jCheckBox15.setSelected(false);
        jCheckBox16.setSelected(false);
        jCheckBox17.setSelected(false);
        jCheckBox18.setSelected(false);
        jCheckBox19.setSelected(false);
        jCheckBox20.setSelected(false);
        jCheckBox21.setSelected(false);
        
        jCheckBox1.setEnabled(true);
        jCheckBox2.setEnabled(true);
        jCheckBox3.setEnabled(true);
        jCheckBox4.setEnabled(true);
        jCheckBox5.setEnabled(true);
        jCheckBox6.setEnabled(true);
        jCheckBox7.setEnabled(true);
        jCheckBox8.setEnabled(true);
        jCheckBox9.setEnabled(true);
        jCheckBox10.setEnabled(true);
        jCheckBox11.setEnabled(true);
       
        jCheckBox13.setEnabled(true);
        jCheckBox14.setEnabled(true);
        jCheckBox15.setEnabled(true);
        jCheckBox16.setEnabled(true);
        jCheckBox17.setEnabled(true);
        jCheckBox18.setEnabled(true);
        jCheckBox19.setEnabled(true);
        jCheckBox20.setEnabled(true);
        jCheckBox21.setEnabled(true);
       
        jButton1.setEnabled(true);
        //jTextArea1.append("remove");
        
        for(int i=0;i<special.size();i++)
        jTextArea1.append(special.get(i)[0]+"  "+special.get(i)[1]+"  "+special.get(i)[2]+"  "+special.get(i)[3]+"\n");
        
        
        for(int i=0;i<special.size();i++){
            //System.out.println(jComboBox2.getSelectedItem());
            if(jComboBox2.getSelectedItem().equals(special.get(i)[0])&&jComboBox1.getSelectedItem().equals(special.get(i)[1])&&jComboBox3.getSelectedItem().equals(special.get(i)[2])){
                if(special.get(i)[3].equals("mon_w1")){
                    jCheckBox1.setEnabled(true);
                    jCheckBox1.setSelected(true);
                }
                if(special.get(i)[3].equals("mon_w2")){
                    jCheckBox6.setEnabled(true);
                    jCheckBox6.setSelected(true);
                }
                if(special.get(i)[3].equals("mon_w3")){
                    jCheckBox11.setEnabled(true);
                    jCheckBox11.setSelected(true);
                }
                if(special.get(i)[3].equals("mon_w4")){
                    jCheckBox17.setEnabled(true);
                    jCheckBox17.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w1")){
                    jCheckBox2.setEnabled(true);
                    jCheckBox2.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w2")){
                    jCheckBox7.setEnabled(true);
                    jCheckBox7.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w3")){
                    jCheckBox13.setEnabled(true);
                    jCheckBox13.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w4")){
                    jCheckBox18.setEnabled(true);
                    jCheckBox18.setSelected(true);
                }if(special.get(i)[3].equals("wed_w1")){
                    jCheckBox3.setEnabled(true);
                    jCheckBox3.setSelected(true);
                }
                if(special.get(i)[3].equals("wed_w2")){
                    jCheckBox8.setEnabled(true);
                    jCheckBox8.setSelected(true);
                }
                if(special.get(i)[3].equals("wed_w3")){
                    jCheckBox14.setEnabled(true);
                    jCheckBox14.setSelected(true);
                }
                if(special.get(i)[3].equals("wed_w4")){
                    jCheckBox19.setEnabled(true);
                    jCheckBox19.setSelected(true);
                }if(special.get(i)[3].equals("thur_w1")){
                    jCheckBox4.setEnabled(true);
                    jCheckBox4.setSelected(true);
                }
                if(special.get(i)[3].equals("thur_w2")){
                    jCheckBox9.setEnabled(true);
                    jCheckBox9.setSelected(true);
                }
                if(special.get(i)[3].equals("thur_w3")){
                    jCheckBox15.setEnabled(true);
                    jCheckBox15.setSelected(true);
                }
                if(special.get(i)[3].equals("thur_w4")){
                    jCheckBox20.setEnabled(true);
                    jCheckBox20.setSelected(true);
                }if(special.get(i)[3].equals("fri_w1")){
                    jCheckBox5.setEnabled(true);
                    jCheckBox5.setSelected(true);
                }
                if(special.get(i)[3].equals("fri_w2")){
                    jCheckBox10.setEnabled(true);
                    jCheckBox10.setSelected(true);
                }
                if(special.get(i)[3].equals("fri_w3")){
                    jCheckBox16.setEnabled(true);
                    jCheckBox16.setSelected(true);
                }
                if(special.get(i)[3].equals("fri_w4")){
                    jCheckBox21.setEnabled(true);
                    jCheckBox21.setSelected(true);
                }
                //System.out.println("bingo");
            }
            
            if(jComboBox2.getSelectedItem().equals(special.get(i)[0])&&(!jComboBox1.getSelectedItem().equals(special.get(i)[1])||!jComboBox3.getSelectedItem().equals(special.get(i)[2]))){
                if(special.get(i)[3].equals("mon_w1")){
                    jCheckBox1.setEnabled(false);
                    jCheckBox1.setSelected(true);
                }
                if(special.get(i)[3].equals("mon_w2")){
                    jCheckBox6.setEnabled(false);
                    jCheckBox6.setSelected(true);
                }
                if(special.get(i)[3].equals("mon_w3")){
                    jCheckBox11.setEnabled(false);
                    jCheckBox11.setSelected(true);
                }
                if(special.get(i)[3].equals("mon_w4")){
                    jCheckBox17.setEnabled(false);
                    jCheckBox17.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w1")){
                    jCheckBox2.setEnabled(false);
                    jCheckBox2.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w2")){
                    jCheckBox7.setEnabled(false);
                    jCheckBox7.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w3")){
                    jCheckBox13.setEnabled(false);
                    jCheckBox13.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w4")){
                    jCheckBox18.setEnabled(false);
                    jCheckBox18.setSelected(true);
                }if(special.get(i)[3].equals("wed_w1")){
                    jCheckBox3.setEnabled(false);
                    jCheckBox3.setSelected(true);
                }
                if(special.get(i)[3].equals("wed_w2")){
                    jCheckBox8.setEnabled(false);
                    jCheckBox8.setSelected(true);
                }
                if(special.get(i)[3].equals("wed_w3")){
                    jCheckBox14.setEnabled(false);
                    jCheckBox14.setSelected(true);
                }
                if(special.get(i)[3].equals("wed_w4")){
                    jCheckBox19.setEnabled(false);
                    jCheckBox19.setSelected(true);
                }if(special.get(i)[3].equals("thur_w1")){
                    jCheckBox4.setEnabled(false);
                    jCheckBox4.setSelected(true);
                }
                if(special.get(i)[3].equals("thur_w2")){
                    jCheckBox9.setEnabled(false);
                    jCheckBox9.setSelected(true);
                }
                if(special.get(i)[3].equals("thur_w3")){
                    jCheckBox15.setEnabled(false);
                    jCheckBox15.setSelected(true);
                }
                if(special.get(i)[3].equals("thur_w4")){
                    jCheckBox20.setEnabled(false);
                    jCheckBox20.setSelected(true);
                }if(special.get(i)[3].equals("fri_w1")){
                    jCheckBox5.setEnabled(false);
                    jCheckBox5.setSelected(true);
                }
                if(special.get(i)[3].equals("fri_w2")){
                    jCheckBox10.setEnabled(false);
                    jCheckBox10.setSelected(true);
                }
                if(special.get(i)[3].equals("fri_w3")){
                    jCheckBox16.setEnabled(false);
                    jCheckBox16.setSelected(true);
                }
                if(special.get(i)[3].equals("fri_w4")){
                    jCheckBox21.setEnabled(false);
                    jCheckBox21.setSelected(true);
                }
            }
        }
        
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox3ItemStateChanged
         // TODO add your handling code here:
        jTextArea1.setText(null);
        
        //jComboBox2.setSelectedIndex(0);
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);
        jCheckBox8.setSelected(false);
        jCheckBox9.setSelected(false);
        jCheckBox10.setSelected(false);
        jCheckBox11.setSelected(false);
        
        jCheckBox13.setSelected(false);
        jCheckBox14.setSelected(false);
        jCheckBox15.setSelected(false);
        jCheckBox16.setSelected(false);
        jCheckBox17.setSelected(false);
        jCheckBox18.setSelected(false);
        jCheckBox19.setSelected(false);
        jCheckBox20.setSelected(false);
        jCheckBox21.setSelected(false);
        
        jCheckBox1.setEnabled(true);
        jCheckBox2.setEnabled(true);
        jCheckBox3.setEnabled(true);
        jCheckBox4.setEnabled(true);
        jCheckBox5.setEnabled(true);
        jCheckBox6.setEnabled(true);
        jCheckBox7.setEnabled(true);
        jCheckBox8.setEnabled(true);
        jCheckBox9.setEnabled(true);
        jCheckBox10.setEnabled(true);
        jCheckBox11.setEnabled(true);
       
        jCheckBox13.setEnabled(true);
        jCheckBox14.setEnabled(true);
        jCheckBox15.setEnabled(true);
        jCheckBox16.setEnabled(true);
        jCheckBox17.setEnabled(true);
        jCheckBox18.setEnabled(true);
        jCheckBox19.setEnabled(true);
        jCheckBox20.setEnabled(true);
        jCheckBox21.setEnabled(true);
       
        jButton1.setEnabled(true);
        //jTextArea1.append("remove");
        
        for(int i=0;i<special.size();i++)
        jTextArea1.append(special.get(i)[0]+"  "+special.get(i)[1]+"  "+special.get(i)[2]+"  "+special.get(i)[3]+"\n");
        
        
        for(int i=0;i<special.size();i++){
            //System.out.println(jComboBox2.getSelectedItem());
            if(jComboBox2.getSelectedItem().equals(special.get(i)[0])&&jComboBox1.getSelectedItem().equals(special.get(i)[1])&&jComboBox3.getSelectedItem().equals(special.get(i)[2])){
                if(special.get(i)[3].equals("mon_w1")){
                    jCheckBox1.setEnabled(true);
                    jCheckBox1.setSelected(true);
                }
                if(special.get(i)[3].equals("mon_w2")){
                    jCheckBox6.setEnabled(true);
                    jCheckBox6.setSelected(true);
                }
                if(special.get(i)[3].equals("mon_w3")){
                    jCheckBox11.setEnabled(true);
                    jCheckBox11.setSelected(true);
                }
                if(special.get(i)[3].equals("mon_w4")){
                    jCheckBox17.setEnabled(true);
                    jCheckBox17.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w1")){
                    jCheckBox2.setEnabled(true);
                    jCheckBox2.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w2")){
                    jCheckBox7.setEnabled(true);
                    jCheckBox7.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w3")){
                    jCheckBox13.setEnabled(true);
                    jCheckBox13.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w4")){
                    jCheckBox18.setEnabled(true);
                    jCheckBox18.setSelected(true);
                }if(special.get(i)[3].equals("wed_w1")){
                    jCheckBox3.setEnabled(true);
                    jCheckBox3.setSelected(true);
                }
                if(special.get(i)[3].equals("wed_w2")){
                    jCheckBox8.setEnabled(true);
                    jCheckBox8.setSelected(true);
                }
                if(special.get(i)[3].equals("wed_w3")){
                    jCheckBox14.setEnabled(true);
                    jCheckBox14.setSelected(true);
                }
                if(special.get(i)[3].equals("wed_w4")){
                    jCheckBox19.setEnabled(true);
                    jCheckBox19.setSelected(true);
                }if(special.get(i)[3].equals("thur_w1")){
                    jCheckBox4.setEnabled(true);
                    jCheckBox4.setSelected(true);
                }
                if(special.get(i)[3].equals("thur_w2")){
                    jCheckBox9.setEnabled(true);
                    jCheckBox9.setSelected(true);
                }
                if(special.get(i)[3].equals("thur_w3")){
                    jCheckBox15.setEnabled(true);
                    jCheckBox15.setSelected(true);
                }
                if(special.get(i)[3].equals("thur_w4")){
                    jCheckBox20.setEnabled(true);
                    jCheckBox20.setSelected(true);
                }if(special.get(i)[3].equals("fri_w1")){
                    jCheckBox5.setEnabled(true);
                    jCheckBox5.setSelected(true);
                }
                if(special.get(i)[3].equals("fri_w2")){
                    jCheckBox10.setEnabled(true);
                    jCheckBox10.setSelected(true);
                }
                if(special.get(i)[3].equals("fri_w3")){
                    jCheckBox16.setEnabled(true);
                    jCheckBox16.setSelected(true);
                }
                if(special.get(i)[3].equals("fri_w4")){
                    jCheckBox21.setEnabled(true);
                    jCheckBox21.setSelected(true);
                }
                //System.out.println("bingo");
            }
            
            if(jComboBox2.getSelectedItem().equals(special.get(i)[0])&&(!jComboBox1.getSelectedItem().equals(special.get(i)[1])||!jComboBox3.getSelectedItem().equals(special.get(i)[2]))){
                if(special.get(i)[3].equals("mon_w1")){
                    jCheckBox1.setEnabled(false);
                    jCheckBox1.setSelected(true);
                }
                if(special.get(i)[3].equals("mon_w2")){
                    jCheckBox6.setEnabled(false);
                    jCheckBox6.setSelected(true);
                }
                if(special.get(i)[3].equals("mon_w3")){
                    jCheckBox11.setEnabled(false);
                    jCheckBox11.setSelected(true);
                }
                if(special.get(i)[3].equals("mon_w4")){
                    jCheckBox17.setEnabled(false);
                    jCheckBox17.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w1")){
                    jCheckBox2.setEnabled(false);
                    jCheckBox2.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w2")){
                    jCheckBox7.setEnabled(false);
                    jCheckBox7.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w3")){
                    jCheckBox13.setEnabled(false);
                    jCheckBox13.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w4")){
                    jCheckBox18.setEnabled(false);
                    jCheckBox18.setSelected(true);
                }if(special.get(i)[3].equals("wed_w1")){
                    jCheckBox3.setEnabled(false);
                    jCheckBox3.setSelected(true);
                }
                if(special.get(i)[3].equals("wed_w2")){
                    jCheckBox8.setEnabled(false);
                    jCheckBox8.setSelected(true);
                }
                if(special.get(i)[3].equals("wed_w3")){
                    jCheckBox14.setEnabled(false);
                    jCheckBox14.setSelected(true);
                }
                if(special.get(i)[3].equals("wed_w4")){
                    jCheckBox19.setEnabled(false);
                    jCheckBox19.setSelected(true);
                }if(special.get(i)[3].equals("thur_w1")){
                    jCheckBox4.setEnabled(false);
                    jCheckBox4.setSelected(true);
                }
                if(special.get(i)[3].equals("thur_w2")){
                    jCheckBox9.setEnabled(false);
                    jCheckBox9.setSelected(true);
                }
                if(special.get(i)[3].equals("thur_w3")){
                    jCheckBox15.setEnabled(false);
                    jCheckBox15.setSelected(true);
                }
                if(special.get(i)[3].equals("thur_w4")){
                    jCheckBox20.setEnabled(false);
                    jCheckBox20.setSelected(true);
                }if(special.get(i)[3].equals("fri_w1")){
                    jCheckBox5.setEnabled(false);
                    jCheckBox5.setSelected(true);
                }
                if(special.get(i)[3].equals("fri_w2")){
                    jCheckBox10.setEnabled(false);
                    jCheckBox10.setSelected(true);
                }
                if(special.get(i)[3].equals("fri_w3")){
                    jCheckBox16.setEnabled(false);
                    jCheckBox16.setSelected(true);
                }
                if(special.get(i)[3].equals("fri_w4")){
                    jCheckBox21.setEnabled(false);
                    jCheckBox21.setSelected(true);
                }
            }
        }
    }//GEN-LAST:event_jComboBox3ItemStateChanged

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
         // TODO add your handling code here:
        jTextArea1.setText(null);
        
        //jComboBox2.setSelectedIndex(0);
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);
        jCheckBox8.setSelected(false);
        jCheckBox9.setSelected(false);
        jCheckBox10.setSelected(false);
        jCheckBox11.setSelected(false);
        
        jCheckBox13.setSelected(false);
        jCheckBox14.setSelected(false);
        jCheckBox15.setSelected(false);
        jCheckBox16.setSelected(false);
        jCheckBox17.setSelected(false);
        jCheckBox18.setSelected(false);
        jCheckBox19.setSelected(false);
        jCheckBox20.setSelected(false);
        jCheckBox21.setSelected(false);
        
        jCheckBox1.setEnabled(true);
        jCheckBox2.setEnabled(true);
        jCheckBox3.setEnabled(true);
        jCheckBox4.setEnabled(true);
        jCheckBox5.setEnabled(true);
        jCheckBox6.setEnabled(true);
        jCheckBox7.setEnabled(true);
        jCheckBox8.setEnabled(true);
        jCheckBox9.setEnabled(true);
        jCheckBox10.setEnabled(true);
        jCheckBox11.setEnabled(true);
       
        jCheckBox13.setEnabled(true);
        jCheckBox14.setEnabled(true);
        jCheckBox15.setEnabled(true);
        jCheckBox16.setEnabled(true);
        jCheckBox17.setEnabled(true);
        jCheckBox18.setEnabled(true);
        jCheckBox19.setEnabled(true);
        jCheckBox20.setEnabled(true);
        jCheckBox21.setEnabled(true);
       
        jButton1.setEnabled(true);
        //jTextArea1.append("remove");
        
        for(int i=0;i<special.size();i++)
        jTextArea1.append(special.get(i)[0]+"  "+special.get(i)[1]+"  "+special.get(i)[2]+"  "+special.get(i)[3]+"\n");
        
        
        for(int i=0;i<special.size();i++){
            //System.out.println(jComboBox2.getSelectedItem());
            if(jComboBox2.getSelectedItem().equals(special.get(i)[0])&&jComboBox1.getSelectedItem().equals(special.get(i)[1])&&jComboBox3.getSelectedItem().equals(special.get(i)[2])){
                if(special.get(i)[3].equals("mon_w1")){
                    jCheckBox1.setEnabled(true);
                    jCheckBox1.setSelected(true);
                }
                if(special.get(i)[3].equals("mon_w2")){
                    jCheckBox6.setEnabled(true);
                    jCheckBox6.setSelected(true);
                }
                if(special.get(i)[3].equals("mon_w3")){
                    jCheckBox11.setEnabled(true);
                    jCheckBox11.setSelected(true);
                }
                if(special.get(i)[3].equals("mon_w4")){
                    jCheckBox17.setEnabled(true);
                    jCheckBox17.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w1")){
                    jCheckBox2.setEnabled(true);
                    jCheckBox2.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w2")){
                    jCheckBox7.setEnabled(true);
                    jCheckBox7.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w3")){
                    jCheckBox13.setEnabled(true);
                    jCheckBox13.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w4")){
                    jCheckBox18.setEnabled(true);
                    jCheckBox18.setSelected(true);
                }if(special.get(i)[3].equals("wed_w1")){
                    jCheckBox3.setEnabled(true);
                    jCheckBox3.setSelected(true);
                }
                if(special.get(i)[3].equals("wed_w2")){
                    jCheckBox8.setEnabled(true);
                    jCheckBox8.setSelected(true);
                }
                if(special.get(i)[3].equals("wed_w3")){
                    jCheckBox14.setEnabled(true);
                    jCheckBox14.setSelected(true);
                }
                if(special.get(i)[3].equals("wed_w4")){
                    jCheckBox19.setEnabled(true);
                    jCheckBox19.setSelected(true);
                }if(special.get(i)[3].equals("thur_w1")){
                    jCheckBox4.setEnabled(true);
                    jCheckBox4.setSelected(true);
                }
                if(special.get(i)[3].equals("thur_w2")){
                    jCheckBox9.setEnabled(true);
                    jCheckBox9.setSelected(true);
                }
                if(special.get(i)[3].equals("thur_w3")){
                    jCheckBox15.setEnabled(true);
                    jCheckBox15.setSelected(true);
                }
                if(special.get(i)[3].equals("thur_w4")){
                    jCheckBox20.setEnabled(true);
                    jCheckBox20.setSelected(true);
                }if(special.get(i)[3].equals("fri_w1")){
                    jCheckBox5.setEnabled(true);
                    jCheckBox5.setSelected(true);
                }
                if(special.get(i)[3].equals("fri_w2")){
                    jCheckBox10.setEnabled(true);
                    jCheckBox10.setSelected(true);
                }
                if(special.get(i)[3].equals("fri_w3")){
                    jCheckBox16.setEnabled(true);
                    jCheckBox16.setSelected(true);
                }
                if(special.get(i)[3].equals("fri_w4")){
                    jCheckBox21.setEnabled(true);
                    jCheckBox21.setSelected(true);
                }
                //System.out.println("bingo");
            }
            
            if(jComboBox2.getSelectedItem().equals(special.get(i)[0])&&(!jComboBox1.getSelectedItem().equals(special.get(i)[1])||!jComboBox3.getSelectedItem().equals(special.get(i)[2]))){
                if(special.get(i)[3].equals("mon_w1")){
                    jCheckBox1.setEnabled(false);
                    jCheckBox1.setSelected(true);
                }
                if(special.get(i)[3].equals("mon_w2")){
                    jCheckBox6.setEnabled(false);
                    jCheckBox6.setSelected(true);
                }
                if(special.get(i)[3].equals("mon_w3")){
                    jCheckBox11.setEnabled(false);
                    jCheckBox11.setSelected(true);
                }
                if(special.get(i)[3].equals("mon_w4")){
                    jCheckBox17.setEnabled(false);
                    jCheckBox17.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w1")){
                    jCheckBox2.setEnabled(false);
                    jCheckBox2.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w2")){
                    jCheckBox7.setEnabled(false);
                    jCheckBox7.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w3")){
                    jCheckBox13.setEnabled(false);
                    jCheckBox13.setSelected(true);
                }
                if(special.get(i)[3].equals("tue_w4")){
                    jCheckBox18.setEnabled(false);
                    jCheckBox18.setSelected(true);
                }if(special.get(i)[3].equals("wed_w1")){
                    jCheckBox3.setEnabled(false);
                    jCheckBox3.setSelected(true);
                }
                if(special.get(i)[3].equals("wed_w2")){
                    jCheckBox8.setEnabled(false);
                    jCheckBox8.setSelected(true);
                }
                if(special.get(i)[3].equals("wed_w3")){
                    jCheckBox14.setEnabled(false);
                    jCheckBox14.setSelected(true);
                }
                if(special.get(i)[3].equals("wed_w4")){
                    jCheckBox19.setEnabled(false);
                    jCheckBox19.setSelected(true);
                }if(special.get(i)[3].equals("thur_w1")){
                    jCheckBox4.setEnabled(false);
                    jCheckBox4.setSelected(true);
                }
                if(special.get(i)[3].equals("thur_w2")){
                    jCheckBox9.setEnabled(false);
                    jCheckBox9.setSelected(true);
                }
                if(special.get(i)[3].equals("thur_w3")){
                    jCheckBox15.setEnabled(false);
                    jCheckBox15.setSelected(true);
                }
                if(special.get(i)[3].equals("thur_w4")){
                    jCheckBox20.setEnabled(false);
                    jCheckBox20.setSelected(true);
                }if(special.get(i)[3].equals("fri_w1")){
                    jCheckBox5.setEnabled(false);
                    jCheckBox5.setSelected(true);
                }
                if(special.get(i)[3].equals("fri_w2")){
                    jCheckBox10.setEnabled(false);
                    jCheckBox10.setSelected(true);
                }
                if(special.get(i)[3].equals("fri_w3")){
                    jCheckBox16.setEnabled(false);
                    jCheckBox16.setSelected(true);
                }
                if(special.get(i)[3].equals("fri_w4")){
                    jCheckBox21.setEnabled(false);
                    jCheckBox21.setSelected(true);
                }
            }
        }
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    
    
    public String query (int num){
        String q="";
        ArrayList<Integer> position_temp=new ArrayList<>();
        for(int i=0;i<amount_position;i++){
            position_temp.add(0);
        }       
        
        for(int i=0;i<person.baseday.position.get(num).size();i++){//position: easy to save in the database
            if(person.baseday.position.get(num).get(i).equals("CC1"))
                position_temp.set(0, 1);
            if(person.baseday.position.get(num).get(i).equals("CC2"))
                position_temp.set(1, 1);
            if(person.baseday.position.get(num).get(i).equals("CC3"))
                position_temp.set(2, 1);
            if(person.baseday.position.get(num).get(i).equals("CC4"))
                position_temp.set(3, 1);
            if(person.baseday.position.get(num).get(i).equals("CC5"))
                position_temp.set(4, 1);
            if(person.baseday.position.get(num).get(i).equals("CC6"))
                position_temp.set(5, 1);
            if(person.baseday.position.get(num).get(i).equals("CC7"))
                position_temp.set(6, 1);
            if(person.baseday.position.get(num).get(i).equals("CC8"))
                position_temp.set(7, 1);
            if(person.baseday.position.get(num).get(i).equals("CC9"))
                position_temp.set(8, 1);
            if(person.baseday.position.get(num).get(i).equals("FC1"))
                position_temp.set(9, 1);
            if(person.baseday.position.get(num).get(i).equals("FC2"))
                position_temp.set(10, 1);
            if(person.baseday.position.get(num).get(i).equals("FC3"))
                position_temp.set(11, 1);
            if(person.baseday.position.get(num).get(i).equals("CCB"))
                position_temp.set(12, 1);
            if(person.baseday.position.get(num).get(i).equals("FC2N"))
                position_temp.set(13, 1);
            if(person.baseday.position.get(num).get(i).equals("FC2CC"))
                position_temp.set(14, 1);
            if(person.baseday.position.get(num).get(i).equals("FC2BU"))
                position_temp.set(15, 1);
            
            
        }
        
        for(int i=0;i<position_temp.size();i++){
            q=q+""+position_temp.get(i)+"";
            if(i<position_temp.size()-1)
                q=q+",";
        }
        return q;
    }
    
     public String non_query (int num){
        String q="";
        ArrayList<Integer> position_temp=new ArrayList<>();
        for(int i=0;i<amount_position;i++){
            position_temp.add(0);
        }       
        
        for(int i=0;i<person.nonbaseday.position.get(num).size();i++){//position: easy to save in the database
            if(person.nonbaseday.position.get(num).get(i).equals("CC1"))
                position_temp.set(0, 1);
            if(person.nonbaseday.position.get(num).get(i).equals("CC2"))
                position_temp.set(1, 1);
            if(person.nonbaseday.position.get(num).get(i).equals("CC3"))
                position_temp.set(2, 1);
            if(person.nonbaseday.position.get(num).get(i).equals("CC4"))
                position_temp.set(3, 1);
            if(person.nonbaseday.position.get(num).get(i).equals("CC5"))
                position_temp.set(4, 1);
            if(person.nonbaseday.position.get(num).get(i).equals("CC6"))
                position_temp.set(5, 1);
            if(person.nonbaseday.position.get(num).get(i).equals("CC7"))
                position_temp.set(6, 1);
            if(person.nonbaseday.position.get(num).get(i).equals("CC8"))
                position_temp.set(7, 1);
            if(person.nonbaseday.position.get(num).get(i).equals("CC9"))
                position_temp.set(8, 1);
            if(person.nonbaseday.position.get(num).get(i).equals("FC1"))
                position_temp.set(9, 1);
            if(person.nonbaseday.position.get(num).get(i).equals("FC2"))
                position_temp.set(10, 1);
            if(person.nonbaseday.position.get(num).get(i).equals("FC3"))
                position_temp.set(11, 1);
            if(person.nonbaseday.position.get(num).get(i).equals("CCB"))
                position_temp.set(12, 1);
            if(person.nonbaseday.position.get(num).get(i).equals("FC2N"))
                position_temp.set(13, 1);
            if(person.nonbaseday.position.get(num).get(i).equals("FC2CC"))
                position_temp.set(14, 1);
            if(person.nonbaseday.position.get(num).get(i).equals("FC2BU"))
                position_temp.set(15, 1);
            
            
        }
        
        for(int i=0;i<position_temp.size();i++){
            q=q+""+position_temp.get(i)+"";
            if(i<position_temp.size()-1)
                q=q+",";
        }
        return q;
    }
    
    public void insert(String q){
        
        Connection conn = null;
        try {
//        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

       // DB d=new DB();
        } catch (java.lang.ClassNotFoundException e) {
            e.printStackTrace();
        }
        //System.out.println("ssssss  ");
        try {
            //conn = DriverManager.getConnection("jdbc:odbc:dbpoolname",  "sa", "123456");  
            conn = DriverManager.getConnection("jdbc:sqlserver://testsql:1433;DatabaseName5=roster", "shahua", "4321");
            System.out.println("connected");
        } catch (SQLException e) {
            System.out.println(e);
        }
       
        
        //String q="insert into users (name, password) values ('Li Gang', '8765')";
        try{
            Statement stmt = conn.createStatement();
            PreparedStatement pstmt = null;
            pstmt=conn.prepareCall(q);
            pstmt.executeUpdate();
            
            stmt.close();
            conn.close();
            System.out.println("inserted");
        }catch (Exception e){
            System.out.println(e);
        }
        
    }
    
    public void load_name(){
        
        Connection conn = null;
        try {
//        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

       // DB d=new DB();
        } catch (java.lang.ClassNotFoundException e) {
            e.printStackTrace();
        }
        //System.out.println("ssssss  ");
        try {
            //conn = DriverManager.getConnection("jdbc:odbc:dbpoolname",  "sa", "123456");  
            conn = DriverManager.getConnection("jdbc:sqlserver://testsql:1433;DatabaseName5=roster", "shahua", "4321");
            System.out.println("connected");
        } catch (SQLException e) {
            System.out.println(e);
        }
        
        ArrayList<String[]> list = new ArrayList<String[]>();
        String q = "use roster select name from name";
        int j = 0;
        try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(q);
            while (rs.next()) {
                j++;
                String note[] = new String[1]; // number of colum which you want to get
                for (int i = 0; i < note.length; i++) {
                    note[i] = (String)rs.getObject(i + 1);
                    //System.out.println(note[i] + "   " + i);
                    //System.out.println(i);
                    note[i]=note[i].trim();
                }
                list.add(note);

            }

            stmt.close();
            conn.close();
            //System.out.println(list.get(0)[0] + "   444");
        } catch (Exception e) {
            System.out.println(e);

        }
        //jComboBox2.addItem("");
        for(int i=0;i<list.size();i++){
            jComboBox2.addItem(list.get(i)[0].trim());
        }
    }
    
    
    public void load_specail(){
            Connection conn = null;
        try {
//        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");

       // DB d=new DB();
        } catch (java.lang.ClassNotFoundException e) {
            e.printStackTrace();
        }
        //System.out.println("ssssss  ");
        try {
            //conn = DriverManager.getConnection("jdbc:odbc:dbpoolname",  "sa", "123456");  
            conn = DriverManager.getConnection("jdbc:sqlserver://testsql:1433;DatabaseName5=roster", "shahua", "4321");
            System.out.println("connected");
        } catch (SQLException e) {
            System.out.println(e);
        }
        
        //ArrayList<Object[]> list = new ArrayList<Object[]>();
        String q = "use roster select name, location, position, day from specialrequire";
        int j = 0;
        try {
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(q);
            while (rs.next()) {
                j++;
                String note[] = new String[4]; // number of colum which you want to get
                for (int i = 0; i < note.length; i++) {
                    note[i] = (String)rs.getObject(i + 1);
                    //System.out.println((String)rs.getObject(i+1));
                    //System.out.println(i);
                    note[i]=note[i].trim();
                }
                special.add(note);

            }

            stmt.close();
            conn.close();
            //System.out.println(special.get(0)[0]);
        } catch (Exception e) {
            System.out.println(e);

        }
        
    }
        
    public ArrayList<Object[]> add_special(String day){
        for(int i=0;i<special.size();i++){
            if(special.get(i)[0].equals(jComboBox2.getSelectedItem())&&special.get(i)[1].equals(jComboBox2.getSelectedItem())&&special.get(i)[2].equals(jComboBox2.getSelectedItem())&&special.get(i)[3].equals(day)){
               //return special;
               
            }
        }
        String[] str=new String[4];
        str[0]=(String)jComboBox2.getSelectedItem();
        str[1]=(String)jComboBox1.getSelectedItem();
        str[2]=(String)jComboBox3.getSelectedItem();
        str[3]=day;
        special.add(str);
        
        return special;
    }
    
    public ArrayList<Object[]> del_special(String sp){
        for(int i=0;i<special.size();i++){
            if(special.get(i)[0].equals((String)jComboBox2.getSelectedItem())&&special.get(i)[1].equals((String)jComboBox1.getSelectedItem())&&special.get(i)[2].equals((String)jComboBox3.getSelectedItem())&&special.get(i)[3].equals(sp)){
                special.remove(i);
               
            }
        }
        return special;
    }
    

    String[] locations_baseday=new String[4];    //?
    String[] locations_nonbaseday=new String[4]; //?
    ArrayList<String> positions_baseday;  //should be [][]
    ArrayList<String> positions_nonbaseday; //??
    static individual_availble baseday;     //??
    static individual_availble nonbaseday;  //??
    ArrayList<String> basedays;             //?
    
    static ArrayList<ArrayList<String>> base=new ArrayList<ArrayList<String>>();     //the positions of base or nonbase day in each location
    static ArrayList<ArrayList<String>> nonbase=new ArrayList<ArrayList<String>>();
    
    String day;        //??
    String name;      //person's name 
    String location;  //get location from list
    static ArrayList<String> all_locations; //??
    int location_value;//??
    individual person; //all information about the person
    private String[] working_day = new String[21]; //the base day or nonbase...
    int amount_position=16; //number of position (cc1 cc2 ...)
    
   ArrayList<Object[]> special = new ArrayList<Object[]>(); //all information from special
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
